image: dchevell/docker-release-maker:latest
clone:
  depth: full

pipelines:
  custom:
    create-release-base-3:
      - step:
          script:
            - git remote set-url origin ${BITBUCKET_GIT_HTTP_ORIGIN}
            - git fetch --all
            - export BASE_BRANCH='base-3'
            - export MAC_PRODUCT_KEY='crowd'
            - export DOCKERFILE_VERSION_STRING='CROWD_VERSION'
            - export DEFAULT_RELEASE='true'
            - export ADDITIONAL_TAG_SUFFIXES='alpine'
            - python /usr/src/app/run.py --create
  branches:
    base-3:
      - step:
          script:
            - git remote set-url origin ${BITBUCKET_GIT_HTTP_ORIGIN}
            - git fetch --all
            - export BASE_BRANCH='base-3'
            - export MAC_PRODUCT_KEY='crowd'
            - export DOCKERFILE_VERSION_STRING='CROWD_VERSION'
            - export DEFAULT_RELEASE='true'
            - export ADDITIONAL_TAG_SUFFIXES='alpine'
            - python /usr/src/app/run.py --update
    release/**:
      - step:
          services:
            - docker
          caches:
            - docker
          script:
            - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - REPO_NAME='dchevell/crowd'
            - IMAGE=$(docker build -q .)
            - >
              for tag in $(git tag -l --points-at HEAD); do
                docker tag "$IMAGE" "${REPO_NAME}":"${tag}";
                docker push "$REPO_NAME":"$tag";
              done